export const Types = {
  GET_WEATHER_DATA: 'GET_WEATHER_DATA',
  GET_WEATHER_DATA_SUCCESS: 'GET_WEATHER_DATA_SUCCESS',
  GET_FORCAST_DATA_SUCCESS: 'GET_FORCAST_DATA_SUCCESS',
  GET_WEATHER_DATA_ERROR: 'GET_WEATHER_DATA_ERROR',
  CHANGE_TEMP_UNIT: 'CHANGE_TEMP_UNIT',
  SET_SELECTED_DATE: 'SET_SELECTED_DATE'
}
